name: wppd-collector-dev

services:
    app:
      build:
        context: ..
        dockerfile: ./docker/Dockerfile.dev
      restart: unless-stopped
      volumes:
        - ../src:/app/src
        - ../logs:/app/logs
        - ../sqlite:/app/sqlite
      environment:
        TZ: "Europe/Berlin"
