services:
  app:
    environment:
      TZ: YOUR_TIMEZONE_HERE
      LOG_LEVEL: YOUR_LOG_LEVEL_HERE
      CORS_WHITELIST: YOUR_COMMA_SEPARATED_LIST_OF_ALLOWED_DOMAINS_HERE
    ports:
      - "YOUR_EXTERNAL_PORT:80"