FROM node:25-alpine AS builder
WORKDIR /app
COPY tsconfig.build.json ./tsconfig.json
COPY package*.json ./
RUN npm install --no-cache
COPY src ./src
RUN npx tsc && npx tsc-alias

FROM node:25-alpine AS runner
WORKDIR /app
COPY tsconfig.build.json ./tsconfig.json
COPY package*.json ./
RUN npm install --omit=dev
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/src/services/database ./src/services/database
COPY sqlite/migrations ./sqlite/migrations
ENV NODE_ENV=production
CMD ["sh", "-c", "npx ts-node src/services/database/Migrate.ts && node dist/index.js"]